### ISSUE TITLE
Directions/Help

### ISSUE THREAD

**Issue by aaleksanyan** [cs-225/RaceGame#2]
Make it so that a new player who's never heard of this game would be able to pick it up easily. This could be done via a button on the main screen or just a static text box or something, because, let's be real - it's not terribly complex. Since it's only going to be a few lines, it could be done by just displaying the instructions at all times.

**Comment by macrzen** [comment]
Let's talk about what we want the directions to say.

**Comment by aaleksanyan** [comment]
RULES

1. Each player is given a start and an end location.
2. You must go to every location on your path from your start to end location. Order does not matter.
3. Each car has randomly assigned attributes that allow for it to travel faster in certain situations. Tires will affect your acceleration, engine will affect your top speed, and weight will affect both to a smaller degree. A higher acceleration means that you travel quicker between points that are closer together. A higher top speed means you will travel quicker between points that are further apart.
4. Click each direction to travel there. The shortest time wins.
